eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://13.207.183.225:9411/api/v2/spans}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

