server:
  port: ${PORT:9000}
  servlet:
    context-path: /notifications

eureka:
  client:
    service-url:
      defaultZone: https://discovery-server-172614450127.asia-south2.run.app/eureka/
  instance:
    hostname: notification-service-4twvjidteq-em.a.run.app
    prefer-ip-address: false
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-port: 443

spring:
  datasource:
    url: jdbc:postgresql://db.tzxyfgbydsstlrzligru.supabase.co:5432/postgres?user=postgres&password=linkedSphere%4012345

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  mail:
    host: smtp.gmail.com
    port: 587
    username: akhandps2002.com@gmail.com
    password: dkgiqqatdzqgmekv

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      enable-auto-commit: false
