spring:
  application:
    name: notification-service

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health

firebase:
  config-path: ${FIREBASE_CONFIG_PATH:classpath:firebase/linkedsphere-dev-firebase-adminsdk-fbsvc-7cc0f51599.json}

