eureka:
  client:
    service-url:
      defaultZone: https://discovery-server-172614450127.asia-south2.run.app/eureka/

spring:
  datasource:
    url: jdbc:postgresql://db.tzxyfgbydsstlrzligru.supabase.co:5432/postgres?user=postgres&password=linkedSphere%4012345

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:linksphere}
    password: ${RABBITMQ_PASSWORD:linksphere}

  data:
    redis:
      host: known-doe-132811.upstash.io
      port: 6379
      username: default
      password: gQAAAAAAAgbLAAIgcDIzYTYyYjY3ZTI1NzI0OGJiODYzMTdiYTQ0OGFjZDM1Ng
      ssl:
        enabled: true

jwt:
  secret: "0f6a9a5e2c5b4d8f3a2b7c9d1e4f6a8b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5"
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
  issuer: "linksphere-auth-service"
