services:
  postgres:
    image: postgres:17-alpine
    container_name: linksphere-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: linksphere
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d linksphere"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: linksphere-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-server:
    image: rishab99058/linksphere-discovery-server:v1.0.0
    container_name: linksphere-discovery-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  gateway-service:
    image: rishab99058/linksphere-gateway-service:v1.0.0
    container_name: linksphere-gateway-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
  
  auth-service:
    image: rishab99058/linksphere-auth-service:v1.0.2
    container_name: linksphere-auth-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      discovery-server:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8082
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/linksphere
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      

  
  user-service:
    image: rishab99058/linksphere-user-service:v1.1.2
    container_name: linksphere-user-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      discovery-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/linksphere
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  
volumes:
  postgres-data:
  redis-data:


# docker exec -it linksphere-postgres psql -U postgres -c "CREATE DATABASE linksphere;"