spring:
  application:
    name: auth-service

  profiles:
    active: local

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8000
  servlet:
    context-path: /auth
