server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/linksphere_auth
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
