server:
  port: ${PORT:7999}
  servlet:
    context-path: /users

eureka:
  client:
    service-url:
      defaultZone: https://linksphere-discovery-server-190262577212.asia-south2.run.app/eureka/

spring:
  datasource:
    url: jdbc:postgresql://pg-3912173-rishab99058-5e60.i.aivencloud.com:20716/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_Xhup2M_IA5IozHRKn2e
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
  cloud:
    openfeign:
      client:
        config:
          auth-service:
            connectTimeout: 2000
            readTimeout: 3000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

jwt:
  secret: "0f6a9a5e2c5b4d8f3a2b7c9d1e4f6a8b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5"
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
  issuer: "linksphere-auth-service"
