spring:
  application:
    name: user-service

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health

resilience4j:
  retry:
    instances:
      auth-service:
        max-attempts: 3
        wait-duration: 1s
