server:
  port: ${PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: https://linksphere-discovery-server-190262577212.asia-south2.run.app/eureka/
  instance:
    prefer-ip-address: false
    hostname: ${SERVICE_HOSTNAME:localhost}
    secure-port-enabled: true
    secure-port: 443
    non-secure-port-enabled: false

spring:
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 100MB
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
              - "https://linksphere-web-190262577212.asia-south2.run.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post/**

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://13.207.183.225:9411/api/v2/spans}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

