// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxu7QQA-FfAQgOmKS1ccn_NNnJkiZShgQ',
    appId: '1:538739406225:web:70afe5fb766288e6f4d630',
    messagingSenderId: '538739406225',
    projectId: 'linkedsphere-dev',
    authDomain: 'linkedsphere-dev.firebaseapp.com',
    storageBucket: 'linkedsphere-dev.firebasestorage.app',
    measurementId: 'G-WP2L3X7DFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4udCWwnWtf3lFg_1Zdp3bALYKeIHP8cQ',
    appId: '1:538739406225:android:d33e8c50181519a3f4d630',
    messagingSenderId: '538739406225',
    projectId: 'linkedsphere-dev',
    storageBucket: 'linkedsphere-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrf5uMR69KAVoO3Nu-SGHrEDuuI71655E',
    appId: '1:538739406225:ios:11da1537fb453833f4d630',
    messagingSenderId: '538739406225',
    projectId: 'linkedsphere-dev',
    storageBucket: 'linkedsphere-dev.firebasestorage.app',
    iosBundleId: 'com.linksphere.linkedsphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrf5uMR69KAVoO3Nu-SGHrEDuuI71655E',
    appId: '1:538739406225:ios:41fd0857d2b3c6d7f4d630',
    messagingSenderId: '538739406225',
    projectId: 'linkedsphere-dev',
    storageBucket: 'linkedsphere-dev.firebasestorage.app',
    iosBundleId: 'com.linksphere.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxu7QQA-FfAQgOmKS1ccn_NNnJkiZShgQ',
    appId: '1:538739406225:web:54f3c52d35975929f4d630',
    messagingSenderId: '538739406225',
    projectId: 'linkedsphere-dev',
    authDomain: 'linkedsphere-dev.firebaseapp.com',
    storageBucket: 'linkedsphere-dev.firebasestorage.app',
    measurementId: 'G-3DWVHGSV31',
  );
}
