name: Backend CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build Project
        working-directory: backend
        run: ./mvnw clean verify -DskipTests
